---

- name: Fetch Cert-Manager Installation script
  ansible.builtin.get_url:
    url: "https://github.com/jetstack/cert-manager/releases/download/{{ cert_manager.version }}/cert-manager.yaml"
    dest: /tmp/cert-manager.yaml
    mode: 0600
- name: Copy Cert-Manager Installation script into place
  ansible.builtin.copy:
    src: /tmp/cert-manager.yaml
    dest: /var/lib/rancher/k3s/server/manifests/cert-manager.yaml
    mode: 0600
    remote_src: true
- name: Install Traefik
  ansible.builtin.template:
    src: traefik.yaml.j2
    dest: /var/lib/rancher/k3s/server/manifests/traefik-ingress.yaml
    mode: 0600
- name: Install Traefik HTTPS Redirect Middleware
  ansible.builtin.template:
    src: traefik-https-redirect-middleware.yaml.j2
    dest: /var/lib/rancher/k3s/server/manifests/traefik-https-redirect-middleware.yaml
    mode: 0600
- name: Install Traefik HSTS Header Middleware
  ansible.builtin.template:
    src: traefik-hsts-header-middleware.yaml.j2
    dest: /var/lib/rancher/k3s/server/manifests/traefik-hsts-header-middleware.yaml
    mode: 0600
- name: Install Let's Encrypt Issuer
  ansible.builtin.template:
    src: letsencrypt-issuer.yaml.j2
    dest: /var/lib/rancher/k3s/server/manifests/letsencrypt-issuer.yaml
    mode: 0600
- name: Configure Rook for managing Ceph storage
  ansible.builtin.import_tasks: rook.yaml
  when: setup_rook
