---

- name: Add Helm apt key
  ansible.builtin.apt_key:
    url: "https://baltocdn.com/helm/signing.asc"
    state: present
- name: Add Helm apt repo
  ansible.builtin.apt_repository:
    repo: "deb https://baltocdn.com/helm/stable/debian/ all main"
    state: present
- name: Install Helm
  ansible.builtin.apt:
    name: ['helm']
    state: present
    update_cache: true
  become: true
- name: Add rook-release chart repo
  kubernetes.core.helm_repository:
    name: rook-release
    repo_url: "https://charts.rook.io/release"
- name: Deploy Rook Operator Helm Chart
  kubernetes.core.helm:
    name: rook-ceph
    chart_ref: rook-release/rook-ceph
    release_namespace: rook-ceph
    create_namespace: true
    kubeconfig: /etc/rancher/k3s/k3s.yaml
    values:
      nodeSelector:
        kubernetes.io/arch: amd64
  become: true
- name: Configure Ceph Cluster
  ansible.builtin.template:
    src: ceph-cluster.yaml.j2
    dest: /var/lib/rancher/k3s/server/manifests/ceph-cluster.yaml
    mode: 0600
- name: Install Ceph Toolbox
  ansible.builtin.template:
    src: ceph-toolbox.yaml.j2
    dest: /var/lib/rancher/k3s/server/manifests/ceph-toolbox.yaml
    mode: 0600
- name: Setup Ceph Block StorageClass
  ansible.builtin.template:
    src: ceph-block-storage-class.yaml.j2
    dest: /var/lib/rancher/k3s/server/manifests/ceph-block-storage-class.yaml
    mode: 0600
- name: Setup Ceph File StorageClass
  ansible.builtin.template:
    src: ceph-file-storage-class.yaml.j2
    dest: /var/lib/rancher/k3s/server/manifests/ceph-file-storage-class.yaml
    mode: 0600
