---

- name: Build a k3s cluster in high availability mode
  hosts: k3s_nodes
  vars:
    k3s_become: true
  roles:
    - role: common
    - role: xanmanning.k3s

- name: Add additional components to Kubernetes control plane
  hosts: k3s_servers
  roles:
    - role: k3s_server

- name: Add k3s Addon Modules
  hosts: homelabx00
  become: true
  roles:
    - role: k3s_addons
