---

- name: Build a k3s cluster with a single control node
  hosts: k3s_nodes
  vars:
    k3s_become_for_all: true
  roles:
    - role: common
    - role: xanmanning.k3s

- name: Add k3s Addon Modules
  hosts: raspberrypi00
  become: yes
  roles:
    - role: k3s-addons
