---

roles:
  - name: xanmanning.k3s
    src: https://github.com/PyratLabs/ansible-role-k3s.git
    version: v3.3.1

collections:
  - name: ansible.utils
    version: 2.8.0
  - name: kubernetes.core
    version: 2.3.2
