---

- name: Install Operator Lifecycle Manager CRDs
  ansible.builtin.get_url:
    url: "https://github.com/operator-framework/operator-lifecycle-manager/releases/download/{{ olm.version }}/crds.yaml"
    dest: /var/lib/rancher/k3s/server/manifests/olm-crds.yaml
- name: Fetch Operator Lifecycle Manager Installation script
  ansible.builtin.get_url:
    url: "https://github.com/operator-framework/operator-lifecycle-manager/releases/download/{{ olm.version }}/olm.yaml"
    dest: /tmp/olm-deployment.yaml
    timeout: 30
- name: Update Operator Lifecycle Manager script to use ARM versions of images
  ansible.builtin.replace:
    path: /tmp/olm-deployment.yaml
    regexp: '@sha256:.*$'
    replace: ":{{ olm.version }}"
- name: Copy Operator Lifecycle Manager Installation script into place
  ansible.builtin.copy:
    src: /tmp/olm-deployment.yaml
    dest: /var/lib/rancher/k3s/server/manifests/olm-deployment.yaml
    remote_src: yes
- name: Fetch Cert-Manager Installation script
  get_url:
    url: "https://github.com/jetstack/cert-manager/releases/download/{{ cert_manager.version }}/cert-manager.yaml"
    dest: /tmp/cert-manager.yaml
- name: Update Cert-Manager script to use ARM versions of images
  ansible.builtin.replace:
    path: /tmp/cert-manager.yaml
    regexp: '(image:((?!-arm).)*):(v.*)$'
    replace: '\1-arm:\3'
- name: Copy Cert-Manager Installation script into place
  ansible.builtin.copy:
    src: /tmp/cert-manager.yaml
    dest: /var/lib/rancher/k3s/server/manifests/cert-manager.yaml
    remote_src: yes
- name: Install Traefik
  ansible.builtin.template:
    src: traefik.yaml.j2
    dest: /var/lib/rancher/k3s/server/manifests/traefik-ingress.yaml
- name: Install Traefik HTTPS Redirect Middleware
  ansible.builtin.template:
    src: traefik-https-redirect-middleware.yaml.j2
    dest: /var/lib/rancher/k3s/server/manifests/traefik-https-redirect-middleware.yaml
- name: Install Traefik HSTS Header Middleware
  ansible.builtin.template:
    src: traefik-hsts-header-middleware.yaml.j2
    dest: /var/lib/rancher/k3s/server/manifests/traefik-hsts-header-middleware.yaml
- name: Install Let's Encrypt Issuer
  ansible.builtin.template:
    src: letsencrypt-issuer.yaml.j2
    dest: /var/lib/rancher/k3s/server/manifests/letsencrypt-issuer.yaml
